### ISSUE TITLE
sharing the code of the CTN model 

### ISSUE THREAD

**Issue by CXEa** [rudylyh/CTN_data#2]
Hi, I was wondering if you would mind sharing the code of the CTN model as well?

**Comment by rudylyh** [comment]
Thanks for your interest.  Please find it here https://github.com/rudylyh/ContourTransformerNetwork

**Comment by CXEa** [comment]
Thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rudylyh/CTN_data"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月26日(星期六) 上午9:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rudylyh/CTN_data] sharing the code of the CTN model  (Issue #2)





 
Thanks for your interest.  Please find it here https://github.com/rudylyh/ContourTransformerNetwork
